name: Hprofile Actions 
on: workflow_dispatch
jobs: 
  Testings:
    runs-on: ubuntu-latest
    steps: 
      - name: code checkout 
        uses: actions/checkout@v4

      - name: Maven test
        run: mvn test

      - name: Checkstyle
        run: mvn checkstyle:checkstyle
     
      - name: Set Java 11
        uses: actions/setup-java@v4
        with :
          distribution: 'temruin'
          java-version: '11'